name=NMEA2000_twai
version=0.1.0
author=Jeremy Boynes
maintainer=Jeremy Boynes
sentence=ESP32 TWAI driver for NMEA2000 library.
paragraph=Driver for the NMEA2000 library using the ESP-IDF TWAI driver.
category=Communication
url=
architectures=*
